### ISSUE TITLE
Double annotation when used with the typescript worker

### ISSUE THREAD

**Issue by rubenfiszel** [TypeFox/monaco-languageclient#476]
At windmill, we use this great library to provide the deno lsp on top of our monaco typescript experience. You can find all the code here: https://github.com/windmill-labs/windmill/blob/main/frontend/src/lib/components/Editor.svelte

It's working extremely well except for one issue: 
![image](https://user-images.githubusercontent.com/275584/229433170-4c54232a-5cbb-476d-a5ce-b503524e3c56.png)

Both the typescript worker, and monaco-languageclient are providing autocompletion and annotation which result in having annoying double annotations for most things.

It's likely that this can only be solved by us making a custom typescript worker but wanted to check with you guys first since it's an important issue for us. I'm happy to sponsor the work on this.

**Comment by CGNonofr** [comment]
@kaisalmen we probable need a simple way to chose which features we want to enable or not

**Comment by rubenfiszel** [comment]
@CGNonofr @kaisalmen Just to be sure, ideally, i'd like to disable the typescript workers output since the deno one is usually of better quality. Furthermore, there are cases where only deno will output annotations so disabling the output of the language-client would not be a great solution.

**Comment by kaisalmen** [comment]
@CGNonofr if I am not mistaken loading monaco-editor only with no language contributions should already do the trick here, but I just had a quick look at the code and that is not done or I overlooked it. 

@rubenfiszel did you try to disable `buildWorkerDefinition`, so you don't get the TypeScript worker. If that works, then these instructions need to be tweaked to only contain the `editorWorker`.

**Comment by rubenfiszel** [comment]
With both no workers, or the editor worker, you have the following error:
with editorWorker
```
Uncaught Error: Unexpected usage
loadForeignModule@http://localhost/workers/editorWorker-iife.js:6:6803
```

without any worker:
```
Uncaught Error: Unexpected usage

loadForeignModule@http://localhost/node_modules/.vite/deps/chunk-HOEHRVR4.js?v=98e13dde:17545:31
node_modules/monaco-editor/esm/vs/editor/browser/services/webWorker.js/_getForeignProxy/this._foreignProxy<@http://localhost/node_modules/.vite/deps/chunk-HOEHRVR4.js?v=98e13dde:18164:26
```

**Comment by rubenfiszel** [comment]
Btw to reproduce this,

The editor code: https://github.com/windmill-labs/windmill/blob/main/frontend/src/lib/components/Editor.svelte

The lsp backend: https://github.com/windmill-labs/windmill/tree/main/lsp

I'm happy to give an hand and explore, I just have no idea where to start.

**Comment by CGNonofr** [comment]
You need to not import 'monaco-editor' directly but edcore file somewhere (I don't remember the exact path but you'll find it)

**Comment by rubenfiszel** [comment]
> You need to not import 'monaco-editor' directly but edcore file somewhere (I don't remember the exact path but you'll find it)

Is there documentation around this ? Why do I not need monaco-editor and solely monaco-editor-core ?

**Comment by kaisalmen** [comment]
We mention it at least in the README:
https://github.com/TypeFox/monaco-languageclient#monaco-editor-core

We should highlight more why it is useful. It provides all editor capabilities without language support. This is especially helpful if you want to just support your own languages. We also do it like this in the examples, but they import what is in `edcore.main.js`. PR #470 will simplify that.

**Comment by kaisalmen** [comment]
> The issue with just importing edcore is that I seem to lose all features, even typescript syntax highlighting (and lsp doesn't work either)

That is expected, because you need to configure the client part as well. Your original problem exists, because you mix monaco client configuration for TypeScript with the Deno language server, I think.

I am not familiar with the Deno Language Server, but I skimmed over the docs real quick. It offers support for JS(X)/TS(X), but the vscode extension contains/configures client parts as well, like language config and Texmate grammars and I think this is what you miss.

I just merged the `monaco-vscode-api` 1.76 branch in. The langium example configures client part this for the DSL used in the example with the new means exposed by `monaco-vscode-api` and the Language Server runs in a web worker:
https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/main/src/langium/main.ts#L57-L92

@CGNonofr do you agree with my analysis? Did I forget something?

**Comment by rubenfiszel** [comment]
@kaisalmen: Makes sense but I could not find the language config and textmate grammars in: https://github.com/denoland/vscode_deno
I assume I could copy the ones from typescript worst case ?

**Comment by CGNonofr** [comment]
It's fine to use the monarch grammar (the default one from monaco editor) instead of the textmate one from the vscode extension, you just need to import it manually (you need to import basic-languages/typescript/typescript.contribution). But it's probably better to be as close as vscode indeed (for semantic tokens for instance) and textmate is much more powerful than monarch.

Deno uses the typescript language which comes from the default vscode extension indeed, and maybe override a few things.

> The issue with just importing edcore is that I seem to lose all features

What features except the colors ?

**Comment by rubenfiszel** [comment]
Sorry to come back late on this, but I was able to make almost everything work perfectly by:

1. Loading in most places edcore + the specific language
2. Make deno a different language and then register the deno language in monaco to load the typescript contribution parts
3. For deno, load  the editor worker instead of the tsWorker

There is one issue which is: in that setup, the websocket for lsp and language client do send back and forth the right messages but nothing is displayed and the autocompletions are not suggested. I'm digging more but any ideas ? At the beginning you mentionned just needing to tweak editorWorker, would that do the trick ?

The current work is at:
https://github.com/windmill-labs/windmill/pull/1370/files

The relevant file is Editor.svelte, the rest of the editors actually deal with typescript/javascript and not with deno files.

**Comment by rubenfiszel** [comment]
This is solved using latest everything and monaco 0.36.0 with the following options:

```
	languages.typescript.typescriptDefaults.setModeConfiguration({
		completionItems: false,
		definitions: false,
		hovers: false
	})
```

**Comment by iSuslov** [comment]
Hey @kaisalmen @rubenfiszel sorry for bothering you here, but do you think there is now a better way of doing this? 
Somehow I don't have `monaco.languages.typescript` defined 😓
I looked at how windmill implements it, but still not being able to figure out my problem.
