### ISSUE TITLE
Rerenders cause editor element to be recreated for MonacoEditorReactComp

### ISSUE THREAD

**Issue by KamWithK** [TypeFox/monaco-languageclient#975]
I created a reproducible example with a purple button where every time you click it will update the text and cause another div to be created:

https://github.com/KamWithK/monaco-languageclient-demo

**Comment by kaisalmen** [comment]
Hi @KamWithK thank you for reporting. I didn't see the solution at first. You have to move the config outside the app, otherwise React sees the need to re-render everything all the time. Use the `modifiedTextValue` for the stateChange. This was introduced with v7.

```ts
const languageClientConfig = createLanguageClientConfig();
const vscodeApiConfig = createVscodeApiConfig();
const editorAppConfig = createEditorAppConfig({
    uri: "/workspace/example.statemachine",
    text,
});

const App = () => {
    const [testState, setTestState] = useState<string>(text);
    return (
        <>
            <button
                style={{background: "purple"}}
                onClick={() => setTestState(testState + "test")}
            />
            <div>
            <div>{testState}</div>
            <MonacoEditorReactComp
                style={{height: "50vh", width: "100vh"}}
                vscodeApiConfig={vscodeApiConfig}
                editorAppConfig={editorAppConfig}
                languageClientConfig={languageClientConfig}
                modifiedTextValue={testState}
            />
            </div>
        </>
    );
};
```

**Comment by KamWithK** [comment]
I am aware that you can structure your code that way and it avoids the problem, but don't think that would work for us

Our actual code for example passes in extra editor options for theme which can change at runtime

It would be good if you just had a editor and language client started ref, so you could fix the bug directly?

**Comment by kaisalmen** [comment]
@KamWithK I suggest to use the `onVscodeApiInitDone`, `onEditorStartDone`, `onLanguageClientsStartDone` callbacks to obtain the `MonacoVscodeApiWrapper`, the `EditorApp` or the `LanguageClientsManager`. Then you can apply your changes directly e.g. apply a new theme in monaco-editor or alter the vscode user config directly, for example.
I realized that it is not clear that the three configuration objects should only be used for initial configuration of the application.  When you don't use the react component this is clear. It was a design choice for the react component we took to ensure the initialization and start-up order of all software pieces it wraps. We must ensure that a different usage does not break the behaviour as you demonstrated.

**Comment by KamWithK** [comment]
> [@KamWithK](https://github.com/KamWithK) I suggest to use the `onVscodeApiInitDone`, `onEditorStartDone`, `onLanguageClientsStartDone` callbacks to obtain the `MonacoVscodeApiWrapper`, the `EditorApp` or the `LanguageClientsManager`. Then you can apply your changes directly e.g. apply a new theme in monaco-editor or alter the vscode user config directly, for example. I realized that it is not clear that the three configuration objects should only be used for initial configuration of the application. When you don't use the react component this is clear. It was a design choice for the react component we took to ensure the initialization and start-up order of all software pieces it wraps. We must ensure that a different usage does not break the behaviour as you demonstrated.

I can't seem to find any other way to set the theme outside of the initial configuration, would you be able to point me towards it or provide a simple example?

**Comment by kaisalmen** [comment]
Hi @KamWithK you can acquire the `EditorApp` like this:
```ts
onEditorStartDone={(editorApp?: EditorApp) => {
    editorAppRef.current = editorApp;
}}
```
where `editorAppRef` is defined as such:
```ts
const editorAppRef = useRef<EditorApp>(undefined);
```
You can update any monaco-editor properties then directly from your app, like switching a theme (where for example the actual theme value could be bound to a state of you app):
```ts
editorAppRef.current?.getEditor()?.updateOptions({ theme: 'vs-dark'});
```
Does that help?

**Comment by KamWithK** [comment]
> Hi @KamWithK you can acquire the `EditorApp` like this:
> ```ts
> onEditorStartDone={(editorApp?: EditorApp) => {
>     editorAppRef.current = editorApp;
> }}
> ```
> where `editorAppRef` is defined as such:
> ```ts
> const editorAppRef = useRef<EditorApp>(undefined);
> ```
> You can update any monaco-editor properties then directly from your app, like switching a theme (where for example the actual theme value could be bound to a state of you app):
> ```ts
> editorAppRef.current?.getEditor()?.updateOptions({ theme: 'vs-dark'});
> ```
> Does that help?

So I tried that but it doesn't seem to do anything for me

Also can still reproduce re-renders when moving config outside of React, just by hitting save in VScode many times (each time causes it to create a new visible element) 

Would it be too much to ask you to fork my example repo and quickly demonstrate the intended way to do this with your library? Thank you for your help and assistance :)

**Comment by kaisalmen** [comment]
> Also can still reproduce re-renders when moving config outside of React, just by hitting save in VScode many times (each time causes it to create a new visible element)

Is this reproducible with your demo above?

> Would it be too much to ask you to fork my example repo and quickly demonstrate the intended way to do this with your library? Thank you for your help and assistance :)

Not immediately, but I will try this week. v7 already reduced the number of re-rendering and StrictMode issues we had, but there seem to be new ones and I would like to remove those issue. Also, if I have good re-production cases, I can distill unit test(s) from those.

**Comment by martin-fleck-at** [comment]
I think I might also be running into the same issue with strict mode. Everything works as expected without it but with strict mode, editors are added more than once and also other things do not work properly, e.g., I cannot use arrow keyboard navigation in the text or trigger auto-completion using Ctrl+Space.

I tried simply disposing the old editorApp when `onEditorStartDone` is triggered but it did not resolve the issue for me. It avoided the multiple rendering problem but the other issues were still present.

Btw, I'm really a big fan of the new version 10 and having everything more or less in one place again! Makes things a lot easier to maintain and the new separation of concerns really makes for a clean initialization, so thank you!

**Comment by kaisalmen** [comment]
> I think I might also be running into the same issue with strict mode. Everything works as expected without it but with strict mode, editors are added more than once and also other things do not work properly, e.g., I cannot use arrow keyboard navigation in the text or trigger auto-completion using Ctrl+Space.

Hi @martin-fleck-at I currently see only completions in one of the two created editors in strict mode. That is either a bug a monaco-editor limitation we can't fix. I need to analyses this. That two editors are shown in StrictMode in general is correct, though.

There is an issue with language clients not being disposed when configured to do so with `enforceDispose`. This needs investigation.

Generally, I need to fix that config adjustment (triggered by react) lead to re-renders. Is anyone of you able to supply a unit test for this scenario that fails now, but should work?

> Btw, I'm really a big fan of the new version 10 and having everything more or less in one place again! Makes things a lot easier to maintain and the new separation of concerns really makes for a clean initialization, so thank you!

Thank you. It's good to hear.

**Comment by martin-fleck-at** [comment]
> Hi [@martin-fleck-at](https://github.com/martin-fleck-at) I currently see only completions in one of the two created editors in strict mode. That is either a bug a monaco-editor limitation we can't fix. I need to analyses this. That two editors are shown in StrictMode in general is correct, though.
> 
> There is an issue with language clients not being disposed when configured to do so with `enforceDispose`. This needs investigation.

Hi @kaisalmen, thank you for the quick follow-up! Could you elaborate a bit on the fact that two editors shown are correct? I do understand that strict mode makes every hook execute twice but even if both editors were usable, I'd only ever expect a single editor instance per component.

If this issue is with `enforceDispose` then I actually may be facing a different problem. My use case is having a React application with multiple React editors but only a single language client, so I don't want to dispose it when any of the editors is disposed. Currently, we take care of initializing Monaco properly, registering our languages and themes and then setting up a single language client that connects to our language server. Based on that overall infrastructure, we render multiple editors to show different, editable, language-specific content. This all works when I'm not using strict mode (even though I always have to provide a `vscodeApiConfig` that will mainly be ignored if `vscodeApiInitialising` is already true except for logging). From what you are saying now, it sounds to me like you are suggesting not to use `MonacoEditorReactComp` in this case?

Edit: I just tried to create a unit test for it but I cannot reproduce it with that. Not sure whether it is my test setup or not. Just on the examples it is much easier to reproduce :(

**Comment by kaisalmen** [comment]
> I do understand that strict mode makes every hook execute twice but even if both editors were usable, I'd only ever expect a single editor instance per component.

Thank you, that is correct and I think I just found the problem. I have to protect the internal logic to be run twice (editor creation in case of StrictMode). I thought I did that properly, but it seems, I didn't. The same applies to language client. I will work on a fix this week.

> From what you are saying now, it sounds to me like you are suggesting not to use MonacoEditorReactComp in this case?

`enforceDispose` must be explicitly set. Per default the language client is not disposed. enforing disposal is just a possibility. It seems I oversaw more life-cycle / re-rendering bugs that effects the language client re-creation / disposal. ⬆️ 

> Edit: I just tried to create a unit test for it but I cannot reproduce it with that. Not sure whether it is my test setup or not. Just on the examples it is much easier to reproduce :(

Thank you. Writing the react tests is not straightforward. Btw, it is possible to use non-headless mode and configure time-outs. Then you can observe what the browser does during the test. This can be really helpful to understand what is going on.

**Comment by KamWithK** [comment]
> > Also can still reproduce re-renders when moving config outside of React, just by hitting save in VScode many times (each time causes it to create a new visible element)
> 
> Is this reproducible with your demo above?
> 

Take a look at my [latest commit](https://github.com/KamWithK/monaco-languageclient-demo/commit/82be2e077d69f3fff8ea8b9e8a47fd4e7a187bb4) for a reproducable demonstration of my issues. The demo is in extended mode unfortunately, but I can still demonstrate the same problems nonetheless. I have changed the buttons action to try and toggle the minimap like you suggested for theme without any luck, and saving in editor will still produce a re-render.

> Not immediately, but I will try this week. v7 already reduced the number of re-rendering and StrictMode issues we had, but there seem to be new ones and I would like to remove those issue. Also, if I have good re-production cases, I can distill unit test(s) from those.

That would be absolutely amazing! I hope my example can aid you in checking everything works fine.

**Comment by kaisalmen** [comment]
@KamWithK and @martin-fleck-at I started to work on this issue (see commit above). Editor is only rendered once in StrictMode now and also only one language client is created. Unit tests are broken and I need still need to fix/check the property based re-rendering problems. Getting there...

**Comment by martin-fleck-at** [comment]
@kaisalmen Thank you very much, that is great news! If you need me to test anything, please let me know!

**Comment by kaisalmen** [comment]
@KamWithK and @martin-fleck-at I have opened a Draft PR and just release next releases, so you can test the fix:
https://www.npmjs.com/package/monaco-languageclient/v/10.3.0-next.0
https://www.npmjs.com/package/@typefox/monaco-editor-react/v/7.3.0-next.0

I am looking forward to your feedback.

**Comment by martin-fleck-at** [comment]
@kaisalmen Wow, thank you very much for the quick fix! I can confirm that for my use case the multiple rendering issue is solved with the new version!

**Comment by martin-fleck-at** [comment]
@kaisalmen It may be unrelated but I managed to get a null access on line 204 where `containerRef.current` is actually null: https://github.com/TypeFox/monaco-languageclient/pull/986/commits/0a4f68106c7b9ff70db17fcc0df89c7981ab2850#diff-bee043747ee6339f6d9c17d89f34c76316c34546f473020e24815fe13ac64db5R204. I'll check whether I can reproduce this with the older version as well.

Edit: I believe it is unrelated but it is also something that only happens in Strict mode. I do have two editors on the same page to trigger this problem.

**Comment by kaisalmen** [comment]
> Edit: I believe it is unrelated but it is also something that only happens in Strict mode. I do have two editors on the same page to trigger this problem.

@martin-fleck-at the runQueue should insure this problem does no longer occur, because creation and disposal do not happen concurrently even with `StrictMode`. You observation implies that the editorApp Ref in two component instances influence each other. I have to test such a scenario. Are you able to reproduce this with a unit test by any chance?

**Comment by martin-fleck-at** [comment]
@kaisalmen I'll try to create a test case a little later today. We also [lazy load](https://react.dev/reference/react/lazy) the monaco editor component so that is an additional factor and I need to figure out whether that has something to do with as well. I don't think so but hopefully the test case will make that more obvious. Will report back and thank you so much already!

**Comment by martin-fleck-at** [comment]
@kaisalmen Hmm... It seems I do not even manage to get two editors render in the same page properly. I tried the following test:

```ts
    test.sequential('strictMode: multiple editors in single render', async () => {
        const firstComponentReady = new Deferred();
        const secondComponentReady = new Deferred();
        const renderResult = render(<StrictMode>
            <div>This is rendered</div>
            <MonacoEditorReactComp
                key='first'
                className='first'
                vscodeApiConfig={vscodeApiConfig}
                editorAppConfig={createSimpleEditorAppConfig('FirstComponent')}
                style={{ 'height': '100px' }}
                onEditorStartDone={() => firstComponentReady.resolve()} />

            <MonacoEditorReactComp
                key='second'
                className='second'
                vscodeApiConfig={vscodeApiConfig}
                editorAppConfig={createSimpleEditorAppConfig('SecondComponent')}
                style={{ 'height': '100px' }}
                onEditorStartDone={() => secondComponentReady.resolve()} />
        </StrictMode>);
        await firstComponentReady.promise;  // onEditorStartDone is actually called twice
        // await secondComponentReady.promise;  // Never seems to be triggered
        await animationFrame();  // ensure component is in DOM after editor start is done, not the best
        renderResult.debug(undefined, -1); // only first component is rendered
        await expect(renderResult.getAllByRole('code')[0].innerText).toEqual('FirstComponent');  // works
        // await expect(renderResult.getAllByRole('code')[1].innerText).toEqual('SecondComponent');  // fails

        cleanHtmlBody();
    });

// helpers

export function animationFrame(): Promise<void> {
    return new Promise(resolve => requestAnimationFrame(() => resolve()));
}

export class Deferred<T = void> {
    promise: Promise<T>;
    resolve: (value: T | PromiseLike<T>) => void;
    reject: (reason?: unknown) => void;

    constructor() {
        this.promise = new Promise<T>((res, rej) => {
            this.resolve = res;
            this.reject = rej;
        });
    }
}
```

This is actually independent from the strict mode, so it is not yet the problem I'm facing but it may be related. Do you have any pointers how I could get that test case to work? I'll pick that up again tomorrow.

**Comment by kaisalmen** [comment]
@martin-fleck-at thank you very much. I fixed the issue. The queue must be global. That was the error.
I incorporated your test and used the Deferred also in other test now. 🎉 

I will release a new next release tomorrow.

**Comment by KamWithK** [comment]
@kaisalmen I tried but am hitting `logger.getLevel is not a function` error

**Comment by kaisalmen** [comment]
@KamWithK  and @martin-fleck-at  new next releases are available:
https://www.npmjs.com/package/monaco-languageclient/v/10.3.0-next.1
https://www.npmjs.com/package/@typefox/monaco-editor-react/v/7.3.0-next.1

> I tried but am hitting logger.getLevel is not a function error

@KamWithK if it does not work with the next.1 versions can you elaborate a bit more where/how this error occurs? #986 fixes many problems, but I have to re-check your initial issue.

**Comment by martin-fleck-at** [comment]
@kaisalmen Thank you for keeping to fix the problems! With the latest version, I run into the issue that the editor itself is not properly loaded. I tracked it down to the fact that `haveEditorService` is false because in my case, I do initialize the MonacoVscodeApiWrapper already outside the editor, so the `apiWrapper` in the editor is always undefined since the monaco environment is already defined, cf:

```ts
let apiWrapper: MonacoVscodeApiWrapper | undefined; // never set by any editor because envEnhanced.vscodeApiInitialising is already true
const lcsManager = new LanguageClientManager();
const haveEditorService = () => {
    return apiWrapper?.getMonacoVscodeApiConfig().viewsConfig.$type === 'EditorService'; // returns false and prevents editor initialization
};
```

Maybe we can use `getEnhancedMonacoEnvironment().viewServiceType` to query the editor service instead of trying to cache the `apiWrapper` here. What do you think?

**Comment by kaisalmen** [comment]
> Maybe we can use getEnhancedMonacoEnvironment().viewServiceType to query the editor service instead of trying to cache the apiWrapper here. What do you think?

@martin-fleck-at  Yes, I even did it as you proposed, but then change it. It breaks tests, but this should be the way forward. I will come back with a solution.

**Comment by kaisalmen** [comment]
@martin-fleck-at I have pushed a fix, but there is no new version, yet. I want to verify the original problem from this issue before as well.

**Comment by kaisalmen** [comment]
@KamWithK I confirm your initial issues is resolved. I have added a unit test that show the dispose is happening after the state change.

I have released new next versions containing the fix the latest problem reported by @martin-fleck-at :
https://www.npmjs.com/package/monaco-languageclient/v/10.3.0-next.2
https://www.npmjs.com/package/@typefox/monaco-editor-react/v/7.3.0-next.2

**Comment by KamWithK** [comment]
> @KamWithK I confirm your initial issues is resolved. I have added a unit test that show the dispose is happening after the state change.

I still seem to get the error I mentioned above, should be easily reproducible with my repo (you will just have to bump those two versions you updated)

Thanks for the updates though, looks like it's close to working now

**Comment by kaisalmen** [comment]
Hi @KamWithK I forked you project and updated to the latest next version. I can no longer reproduced the original problem. This looks good now:
https://github.com/kaisalmen/monaco-languageclient-demo

**Comment by martin-fleck-at** [comment]
> I have released new next versions containing the fix the latest problem reported by [@martin-fleck-at](https://github.com/martin-fleck-at) : https://www.npmjs.com/package/monaco-languageclient/v/10.3.0-next.2 https://www.npmjs.com/package/@typefox/monaco-editor-react/v/7.3.0-next.2


@kaisalmen Thank you very much for the update! I think the overall changes look good and it did solve the problem of not starting up the editor for me. Unfortunately, I'm still encountering this error in strict mode:
```
dom.js:578 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
    at getShadowRoot (dom.js:578:20)
    at isInShadowDOM (dom.js:575:14)
    at StandaloneThemeService.registerEditorContainer (standaloneThemeService.js:222:13)
    at new StandaloneEditor2 (standaloneCodeEditor.js:165:51)
    at new <anonymous> (injection.js:16:13)
    at new ConfiguredStandaloneEditor (monaco.js:86:13)
    at _InstantiationService._createInstance (instantiationService.js:129:24)
    at _InstantiationService.createInstance (instantiationService.js:103:27)
    at Object.createConfiguredEditor [as create] (monaco.js:298:10)
    at EditorApp.createEditors (editorApp.ts:223:41)
```

caused by `containerRef.current` being `null`. Unfortunately, I did not manage to write a proper test for it. I only encounter it in our project so far, cf. https://github.com/axonivy/process-editor/pull/1220. I will further investigate but for now the workaround is simply to avoid strict mode. Simply guarding against the null condition does not solve the problem, seemingly.

**Comment by kaisalmen** [comment]
@CGNonofr any idea on the above error (https://github.com/TypeFox/monaco-languageclient/issues/975#issuecomment-3496588999)?

**Comment by CGNonofr** [comment]
It looks like an editor is created on a dom element `undefined` 🤔

**Comment by KamWithK** [comment]
> Hi [@KamWithK](https://github.com/KamWithK) I forked you project and updated to the latest next version. I can no longer reproduced the original problem. This looks good now: https://github.com/kaisalmen/monaco-languageclient-demo

Thanks, I'll take a look at what you have done then
Can modify the example of mine later today if I still encounter problems

**Comment by KamWithK** [comment]
So updated everything like you did and have some progress finally
I no longer get any re-renders, but having issues in our actual app with notification handler not being called after a re-render despite `languageClient.onNotification(...)` being called within the `onLanguageClientsStartDone` callback

I'm trying to find out how to encorporate that into my demo so you can easily reproduce the issue, but though I'd just quickly update on my progress testing this version

**Comment by kaisalmen** [comment]
@KamWithK  and @martin-fleck-at new next releases are available. The reflect the latest status from PR #986 :
https://www.npmjs.com/package/monaco-languageclient/v/10.3.0-next.3
https://www.npmjs.com/package/@typefox/monaco-editor-react/v/7.3.0-next.3

The editor is no longer destroyed on re-rendering, but only if the component is unmounted. `onEditorStartDone` is therefore only called once. `onConfigProcessed` is used if the `editorOptions` or `codeResources` are changed in `editorAppConfig`. This made it stable in all scenarios (StrictMode, multiple components). The unit tests verify this now, too.

**Comment by KamWithK** [comment]
> [@KamWithK](https://github.com/KamWithK) and [@martin-fleck-at](https://github.com/martin-fleck-at) new next releases are available. The reflect the latest status from PR [#986](https://github.com/TypeFox/monaco-languageclient/pull/986) : https://www.npmjs.com/package/monaco-languageclient/v/10.3.0-next.3 https://www.npmjs.com/package/@typefox/monaco-editor-react/v/7.3.0-next.3
> 
> The editor is no longer destroyed on re-rendering, but only if the component is unmounted. `onEditorStartDone` is therefore only called once. `onConfigProcessed` is used if the `editorOptions` or `codeResources` are changed in `editorAppConfig`. This made it stable in all scenarios (StrictMode, multiple components). The unit tests verify this now, too.

I tried to bump the deps but I can't seem to `npm run build` without getting GC heap out of memory errors (tried on a few computers)

I have now updated my repo which exhibits the problem: https://github.com/KamWithK/monaco-languageclient-demo

**Comment by kaisalmen** [comment]
> I have now updated my repo which exhibits the problem: https://github.com/KamWithK/monaco-languageclient-demo

@KamWithK thank you. I analyse it and come back with a solution (I have may already have an idea).

**Comment by kaisalmen** [comment]
>I tried to bump the deps but I can't seem to npm run build without getting GC heap out of memory errors (tried on a few computers)

@KamWithK I have found the issue and fixed others as well. New preview release will come tomorrow. I have already pushed an update to the PR branch.

**Comment by KamWithK** [comment]
> > I tried to bump the deps but I can't seem to npm run build without getting GC heap out of memory errors (tried on a few computers)
> 
> [@KamWithK](https://github.com/KamWithK) I have found the issue and fixed others as well. New preview release will come tomorrow. I have already pushed an update to the PR branch.

Awesome thank you!

**Comment by KamWithK** [comment]
Something else we found (I haven't checked, you could've already noticed and fixed it) is if you have several instances of Monaco language client, only the first `vscodeApiConfig` gets respected (`performGlobalInit` was defined outside the component)

**Comment by kaisalmen** [comment]
@KamWithK and @martin-fleck-at new preview releases are out:
https://www.npmjs.com/package/monaco-languageclient/v/10.3.0-next.4
https://www.npmjs.com/package/@typefox/monaco-editor-react/v/7.3.0-next.4

> only the first vscodeApiConfig gets respected (performGlobalInit was defined outside the component)

The monaco-vscode-api can only be configure once. Therefore you can even do this without the react component dealing with it. It is now no longer a required property, but if you never started it and don't provide it, there will be an error thrown now.
The languageclient will on be disposed if you add the `enforceDispose` to its config. The statemachine demo now has buttons to test this and the unit tests deal with it properly.

The OOM errors resulted from exceptions being thrown in the queue processing that weren't catched. This is now handled and the never ending checking problems are gone.

Looking forward to your feedback.

**Comment by kaisalmen** [comment]
New preview builds address problem when component is used without monaco-vscode-api and it unifies the error handling for all code paths:
https://www.npmjs.com/package/monaco-languageclient/v/10.3.0-next.5
https://www.npmjs.com/package/@typefox/monaco-editor-react/v/7.3.0-next.5

**Comment by kaisalmen** [comment]
New preview releases are available:
https://www.npmjs.com/package/monaco-languageclient/v/10.3.0-next.6
https://www.npmjs.com/package/@typefox/monaco-editor-react/v/7.3.0-next.6

**Comment by KamWithK** [comment]
> New preview releases are available: https://www.npmjs.com/package/monaco-languageclient/v/10.3.0-next.6 https://www.npmjs.com/package/@typefox/monaco-editor-react/v/7.3.0-next.6

I have tried this, v4 and v5 out, and I still can't seem to `npm run build` without errors

**Comment by KamWithK** [comment]
`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

**Comment by KamWithK** [comment]
Okay I did manage to get past that by removing the lock files and node modules and things seem to work pretty well now

Only real problem which I can see atm is that changing the log level doesn't actually seem to do anything for some reason, not sure why? I changed all my log levels one per config to error but I still am seeing debug logs from Monaco language client in the console 

Something else is when the editor is already created it seems to still reset its contents (not sure if this is on our end though, haven't tried doing it in the reproducible example)

**Comment by kaisalmen** [comment]
@KamWithK next-5 was a bad one, sorry. next-6 fixed editor typing / config sync issue. I will look into the logging issue.

> Something else is when the editor is already created it seems to still reset its contents (not sure if this is on our end though, haven't tried doing it in the reproducible example)

Was that with next.5 or next.6?

**Comment by kaisalmen** [comment]
> I will look into the logging issue.

@KamWithK that was easy I pushed an update, but there is no new build, yet: https://github.com/TypeFox/monaco-languageclient/pull/986/commits/e38884e46d14dcb9f229008dde56aa23516c2348

**Comment by KamWithK** [comment]
> @KamWithK next-5 was a bad one, sorry. next-6 fixed editor typing / config sync issue. I will look into the logging issue.
> 
> > Something else is when the editor is already created it seems to still reset its contents (not sure if this is on our end though, haven't tried doing it in the reproducible example)
> 
> Was that with next.5 or next.6?

Was next.6

**Comment by kaisalmen** [comment]
Final releases are available since yesterday:
https://www.npmjs.com/package/monaco-languageclient/v/10.3.0
https://www.npmjs.com/package/@typefox/monaco-editor-react/v/7.3.0

**Comment by KamWithK** [comment]
Updated my reproducible example to the new version so you can see the build error

**Comment by kaisalmen** [comment]
@KamWithK you have to use the new major version `^23` of monaco-vscode-api with the final version. If you mix `^22` and `^23` (via `x.3.0` versions) you will have build issues.

**Comment by KamWithK** [comment]
> @KamWithK you have to use the new major version `^23` of monaco-vscode-api with the final version. If you mix `^22` and `^23` (via `x.3.0` versions) you will have build issues.

Yeah I figured that out eventually haha

Now my only issue left is the text resettings when the editor is recreated

**Comment by kaisalmen** [comment]
> Now my only issue left is the text resettings when the editor is recreated

Is that reproducible with the above demo?

**Comment by kaisalmen** [comment]
@KamWithK a new next release is available (only the component this time), see #997 :
https://www.npmjs.com/package/@typefox/monaco-editor-react/v/7.4.0-next.0

**Comment by KamWithK** [comment]
> @KamWithK a new next release is available (only the component this time), see #997 :
> https://www.npmjs.com/package/@typefox/monaco-editor-react/v/7.4.0-next.0

Yeah this does seem to fix my issue, thanks! Will this go into a stable release soon or will it just stick around as a preview (`next`) release?

**Comment by kaisalmen** [comment]
> Yeah this does seem to fix my issue, thanks! Will this go into a stable release soon or will it just stick around as a preview (next) release?

@KamWithK great news. I was able to reproduce your problem while working on the fix and I hope that both issues are gone now. I am waiting for feedback. If that is positive a release will follow soon.
